<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DNQ8BVN" failures="1" tests="1" name="Unit Test" time="0.047" errors="0" timestamp="2021-02-01T09:28:58 EET">
  <testcase classname="test.NewTest" name="test" time="0.003">
    <failure type="java.lang.RuntimeException" message="ERROR">
      <![CDATA[java.lang.RuntimeException: ERROR
at test.NewTest.test(NewTest.java:10)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Unit Test -->
