<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-01T09:28:58 EET" name="Tests" finished-at="2021-02-01T09:28:58 EET" duration-ms="47">
    <groups>
    </groups>
    <test started-at="2021-02-01T09:28:58 EET" name="Unit Test" finished-at="2021-02-01T09:28:58 EET" duration-ms="47">
      <class name="test.NewTest">
        <test-method signature="test()[pri:0, instance:test.NewTest@bcec361]" started-at="2021-02-01T09:28:58 EET" name="test" finished-at="2021-02-01T09:28:58 EET" duration-ms="3" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ERROR]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ERROR
at test.NewTest.test(NewTest.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- test.NewTest -->
    </test> <!-- Unit Test -->
  </suite> <!-- Tests -->
</testng-results>
